# Generated by Django 3.1.2 on 2020-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essapp', '0003_auto_20201028_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
